# Generated by Django 3.0.3 on 2024-02-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_auto_20240205_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receipe',
        ),
    ]
